Feature/layout
PotenFinance/Frontend pull request #6
Opened 2024-12-09 17:02 UTC by danimkim

## 📝 작업 내용

1. color theme 및 폰트 추가
총 3가지 폰트 중 페이퍼로지 및 에스코어드림 폰트는 웹폰트로 추가하였는데 프리텐다드JP는 웹폰트로 못 찾아서 폰트 파일을 다운 받아서 추가하였습니다.

2. global styles 추가

- emotion에서 제공하는 `Global` 컴포넌트로 전역 스타일 추가 (`styles/globals.ts` 파일에서 css 확인가능)
- 주석으로 reset css라고 주석으로 표시해둔 이하에는 reset css를 추가하면 됩니다.

3. 공통 레이아웃 추가(WIP)
논의된대로 min-width: 390px, max-width:600px 의 뷰포트를 기준으로 레이아웃을 설정하였습니다. 현재는 탭만 임의로 추가되어있는 상태입니다.

|공통 레이아웃 적용된 홈화면|
|:-:|
|![image](https://github.com/user-attachments/assets/f0d37901-6195-471c-a0a4-efbbf9bc8d4e)|

2024-12-09 18:28 UTC, yujinyny requested changes
고생하셨습니다 !!

아직 아이콘은 추가 안하신걸까요 ?!

2024-12-09 18:28 UTC, yujinyny commented on src/components/layout/index.tsx
> +      <Nav>
추후에 `constant`로 분리하여 관리하면 좋을거 같습니다 :) + 컴포넌트 분리

2024-12-09 18:28 UTC, yujinyny commented on src/pages/_app.tsx
> +      <Global styles={global} />
`<Global />`을 `<Layout />` 상단에 배치하지 않아도 문제 없나요?

2024-12-09 18:28 UTC, yujinyny commented on src/styles/globals.ts
> +    font-weight: 600;
600이 아니라 700인거 같아요!

2024-12-09 18:28 UTC, yujinyny commented on src/styles/theme.ts
> +export const lightTheme: Theme = {
다님님 피그마에 정의된 컬러 디자인 가이드랑 분류가 다른거 같은데 혹시 맞을까요?
그렇다면 전 피그마에 정의된 것과 똑같이 가야된다고 생각합니다 :( (디자인팀과 커뮤니케이션, 피그마에서 색상 확인하기 어려움)

그리고 타이포그래피도 정의 부탁드려요!

2024-12-09 18:42 UTC, danimkim commented on src/components/layout/index.tsx
> +      <Nav>
~~앗 어떤거 constant 얘기하시나요?~~
아 Nav탭 말씀하시는거군요! 네네 Nav 컴포넌트 따로 분리하고 nav 메뉴명 constant로 뺄 예정입니다 다음 pr 때 올리겠습니다

2024-12-09 18:44 UTC, danimkim commented on src/pages/_app.tsx
> +      <Global styles={global} />
아 이거는 제가 테스트 하다가 잘못 위치시킨거 같습니다 최상단에 배치하는게 맞습니다 수정할게요!

2024-12-09 18:57 UTC, danimkim commented on src/styles/theme.ts
> +export const lightTheme: Theme = {
아 그렇군요 디자인팀과 협업 측면을 고려하면 말씀하신게 맞는거 같네요 그렇다면 현재 피그마에 정의되어있는 컬러 하단의 이름으로 정의하면될까요?

**예시**
|Theme| Brand|
|:-:|:-:|
|![image](https://github.com/user-attachments/assets/5a51776e-cb6f-4433-a99f-60d834a33fa6)|![image](https://github.com/user-attachments/assets/600a498b-8507-46d0-a2d1-e965d16258a3)|

```js
color: {
  theme: {
   positive: '#00C48C',
   negative: '#FF0000',
   // ...
   OTT: '#90131E',
  'music': '#F44336'
  // ....
  },
  brand: {
    netflix: 'E50491'
    // ...
  }
}
```

타이포그래피 정의 추가하겠습니다!

2024-12-09 19:07 UTC, danimkim commented on src/styles/globals.ts
> +    font-weight: 600;
에스코어드림 font-weight 말씀이신가요? 
피그마에 Bold 로 되어있어서 찾아보니 해당 font-weight가 600 으로 나와있어서 600으로 적었습니다
혹 제가 잘못 찾은거라면 다시 말씀해주세요!

![image](https://github.com/user-attachments/assets/812e988b-a8ee-4fb3-a231-304e820e84d4)

2024-12-09 19:55 UTC, yujinyny commented on src/styles/globals.ts
> +    font-weight: 600;
바로 옆에 있는 Bold는 700인거 보면 디자이너분이 잘못 적으신거 아닐까 하네요!!

<img width="285" alt="스크린샷 2024-12-10 오전 4 54 32" src="https://github.com/user-attachments/assets/e6cf3295-844e-4e57-b3f7-a02afbd498c8">

2024-12-09 19:56 UTC, yujinyny commented on src/styles/theme.ts
> +export const lightTheme: Theme = {
네네 예시대로 하면 될 거 같습니다!

2024-12-09 20:38 UTC, danimkim commented
> 고생하셨습니다 !!
> 
> 아직 아이콘은 추가 안하신걸까요 ?!

네 아이콘은 아직 추가하지 못했습니다ㅠ 다음 pr 때 추가해서 올리겠습니다!

2024-12-09 20:40 UTC, danimkim reviewed
Global 컴포넌트 최상단 위치 및 theme color 타입 수정, 타이포그래피 타입 정의 추가하였습니다

2024-12-10 05:32 UTC, yujinyny approved these changes
고생하셨습니다!

2024-12-10 05:32 UTC, merged